language: node_js

node_js:
  - '8'

python:
  - '2.7'

cache:
  - pip
  - yarn
  directories:
  - "$HOME/google-cloud-sdk/"

notifications:
  - email: false

env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    curl -O https://raw.githubusercontent.com/GoogleCloudPlatform/continuous-deployment-circle/master/scripts/fetch_gae_sdk.py
    python ./fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
    curl https://sdk.cloud.google.com | bash;
  fi
