language: node_js

node_js:
  - '8'

python:
  - '2.7'

cache:
  pip: true
  yarn: true
  directories:
  - "$HOME/google-cloud-sdk/"
  - node_modules

notifications:
  - email: false

env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install app-engine-python

before_script:
  - npm install --global gulp-cli
  
script: 
  - yarn test
  - gulp deploy --dryrun
